config/routes.rb
Ketchum::Application.routes.draw do
  
  resources :videos

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  resources :admins, only: [:new, :create, :destroy]
  root to: 'home#index'

  match '/about', to: 'home#about'
  match '/contact', to: 'home#contact'
  match '/home', to: 'home#index'
  match '/work', to: 'home#work'
  match '/video_player', to: 'home#video'
  match '/team', to: 'home#team'
  match '/client', to: 'home#client'

  
  
  

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :brand, :description, :director, :permalink, :project, :type_of, :url, :posterframe, :producer, :image

  after_create :create_permalink
  
  validates_inclusion_of :type_of, :in => ['film', 'television', 'digital'], :message => "attribute :type_of must be 'film, television, or digital' "
  
  self.class_eval do
    scope :previous,  lambda { |i| {:conditions => ["#{self.table_name}.id < ?", i], :order => "#{self.table_name}.id DESC", :limit => 1 }}
    scope :next,      lambda { |i| {:conditions => ["#{self.table_name}.id > ?", i], :order => "#{self.table_name}.id ASC",  :limit => 1 }}
  end
  
  scope :film,        where(:type_of => 'film')
  scope :television,  where(:type_of => 'television')
  scope :digital,     where(:type_of => 'digital')
  
  private
    
    def create_permalink
      number = "546708330517"
      index = self.id
      self.permalink = "#{index}#{number}"
      self.save!
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find_by_permalink(params[:id])
    
    previous_video = Video.previous(@video)
    if previous_video.empty?
      @previous = Video.last.permalink
    else
      @previous = previous_video.pop.permalink
    end
    
    next_video = Video.next(@video)
    if next_video.empty?
      @next = Video.first.permalink
    else
      @next = next_video.pop.permalink
    end
    # we may need some cant find permalink screen  
    
    @text_size = @video.project.size < 35 ? "textTitle" : "textTitleSmall"    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project %><br />
    <%= f.text_field :project %>
  </div>
  <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :type_of %><br />
    <%= f.text_field :type_of %>
  </div>
  <div class="field">
    <%= f.label :director %><br />
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :permalink %><br />
    <%= f.text_field :permalink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/_playerWrapper.html.erb
<div class="playerWrapper">
	<div class="videoNav">
		<h3 class='nextButton'><%= link_to "Next->", video_path(@next), :class => "backClick" %><br /><%= link_to "<-Back", video_path(@previous), :class => "backClick" %></h3>
	</div>

    <div class="closeButton">
      <h3 class="closeX"><%= link_to "[X]", work_path %></h3>
    </div>

	<div class="videoInfo">
  			<h3 class="title">
  				<span class="whiteBackground">Project:</span>
  			</h3>
  			<h3 class="<%= @text_size %>">
  				<span class="whiteBackground"><%= @video.project %></span>
  			</h3>
  			<h3 class="networkBrand">
  				<span class="tanBackground">Network/Brand:</span>
  			</h3>
  			<h3 class="networkBrandText">
  				<span class="tanBackground"><%= @video.brand %></span>
  			</h3>
  			<h3 class="type">
  				<span class="tanBackground">Type:</span>
  			</h3>
  			<h3 class="typeText">
  				<span class="tanBackground"><%= @video.type_of.capitalize %></span>
  			</h3>
  			<% if @video.director %>
    			<h3 class="director">
    				<span class="tanBackground">Director:</span>
    			</h3>
    			<h3 class="directorText">
    				<span class="tanBackground"><%= @video.director %></span>
    			</h3>
  			<% end %>
  			<% if @video.producer %>
    			<h3 class="director">
    				<span class="tanBackground">Producer:</span>
    			</h3>
    			<h3 class="directorText">
    				<span class="tanBackground"><%= @video.producer %></span>
    			</h3>
  			<% end %>
  	</div>
  	
    <div class="videoContainer">
      <%= render 'video_legit'  %>
    </div>
  </div>

<h3 class="tabTitle">
	<%= @video.type_of.capitalize %>
</h3>

<div class="playerLongInfo">
	
	<h3 class="descriptionText">
      <%= @video.description %>		
    </h3>
</div>

app/views/videos/_video.html.erb
<div class="z-indexer">  
  <video id="mediaplayer"
      width="652"
      height="369"
      src="<%= @video.url %>"
      poster="<%= @video.image %>"
      preload="auto">
  </video>
</div>




<script type="text/javascript">
  jwplayer('mediaplayer').setup({
     'flashplayer': 'http://player.longtailvideo.com/player.swf'
  });
</script>

app/views/videos/_video_legit.html.erb
<div  class="z-indexer">
  <div id="container">Loading the player ...</div>
</div>


<script type="text/javascript">
  jwplayer("container").setup({
    flashplayer: "/jwplayer/player.swf",
    file: "<%= @video.url %>",
    autostart: true,
    height: 369,
    width: 652,
    image: "<%= @video.image %>",
    skin: "/skins/glow/glow.xml"
  });
  // jwplayer('container').oncanplaythrough(function() { 
  // 	alert('inside oncanplaythrough');
  // 	this.play();
  // });
</script>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <tr>
    <th>Project</th>
    <th>Brand</th>
    <th>Type of</th>
    <th>Director</th>
    <th>Url</th>
    <th>Description</th>
    <th>Permalink</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.project %></td>
    <td><%= video.brand %></td>
    <td><%= video.type_of %></td>
    <td><%= video.director %></td>
    <td><%= video.url %></td>
    <td><%= video.description %></td>
    <td><%= video.permalink %></td>
    <td><%= link_to 'Show', video %></td>
    <td><%= link_to 'Edit', edit_video_path(video) %></td>
    <td><%= link_to 'Destroy', video, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<div class="workWrapper">
	<div class="roundedNav"></div>
	<div class="logoDots"></div>

	<%= render :partial => 'playerWrapper' %>

	<div class="navTextWrapper">
    	<h2  class="navSelected"><%= link_to "the work", work_path %></h2>
    	<h2><%= link_to "the team", team_path %></h2>
    	<h2><%= link_to "contact", contact_path %></h2>
    	<h2><%= link_to "client", client_path %></h2>
  </div>
  	
</div> <!--! End workWrapper -->