config/routes.rb
Ketchum::Application.routes.draw do
  
  resources :videos

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  resources :admins, only: [:new, :create, :destroy]
  root to: 'home#index'

  match '/about', to: 'home#about'
  match '/contact', to: 'home#contact'
  match '/home', to: 'home#index'
  match '/work', to: 'home#work'
  match '/video_player', to: 'home#video'
  match '/team', to: 'home#team'
  match '/client', to: 'home#client'

  
  
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  
  def contact
  end
  
  def work
    if params[:q]    
      @filter = ".#{params[:q]}" 
    else
      @filter = ".all"
    end
    # if params[:offset] == '8'
    #   @videos = Video.limit(8).offset(params[:offset])
    #   @back = 16
    #   @forward = nil
    # elsif params[:offset] == '16'
    #   @videos = Video.limit(8).offset(params[:offset])
    #   @back = nil
    #   @forward = 8
    # else
    #   @videos  = Video.limit(8)
    #   @back = 8
    #   @forward = 16
    # end 
    video_full    = Video.limit(24)
    #  split videos up for the carousel - 8 in each frame
    @videos       = video_full[0..7]
    @videos_left  = video_full[8..15]
    @videos_right = video_full[16..23]


  end
  
  def video
    @video = Video.first
  end

end

app/views/home/_posterframeCell.html.erb
<%  videos.each do |video| %>
   <div class="posterframeCell">
     <div class="itemCell"><%= image_tag video.posterframe  %></div>
     <div class="clearBox <%= video.type_of %>"></div>
     <div class="playButton"><%= link_to "" , video_path(video.permalink) %></div>
   </div>
<% end %>

app/views/home/_videoSelector.html.erb
<div class="paperSort videoSelector"></div>

<div class="checkBoxWrapper videoSelector">
	<div id="filters">
		<h2 class="filmFilter">
		  <a href="#" data-filter=".film">Film</a>
			<div class="filmBox checkBox"></div>
			<div class="filmCheck checkMark "></div>
		</h2>
		<h2 class="televisionFilter">
		  <a href="#" data-filter=".television">Television</a>
        <div class="televisionBox checkBox"></div>
        <div class="televisionCheck checkMark "></div>
		</h2>
		
		<h2 class="digitalFilter">
		  <a href="#" data-filter=".digital">Digital</a>
			<div class="digitalBox checkBox"></div>
			<div class="digitalCheck checkMark "></div>
		</h2>	
		<h2 class="allFilter">
		  <a href="#" data-filter=".all">All</a>
			<div class="allBox checkBox"></div>
			<div class="allCheck checkMark"></div>
		</h2>		
	</div>
</div>

<div class="videoBorder videoSelector"></div>
  	<div class="paginateVideos">
  		<h3>
  			<!-- Carousel nav -->
        <a class="backButton left" href="#myCarousel" data-slide="prev"><===</a>
        &nbsp;&nbsp; Page &nbsp;&nbsp;
        <a class="backButton right" href="#myCarousel" data-slide="next">===></a>
  		</h3>
  	</div>
  <div class="containerVideos">
    <div id="myCarousel" class="carousel slide">
      <!-- Carousel items -->
      <div class="carousel-inner">
      <div class="active item">
          <%= render 'posterframeCell', :videos => @videos %>
      </div>
      <div class="item">
          <%= render 'posterframeCell', :videos => @videos_left %>
      </div>
      <div class="item">
          <%= render 'posterframeCell', :videos => @videos_right %>
      </div>
      </div>
    </div>
  </div>

app/views/home/about.html.erb
<div class="center hero-unit">
  <div class="row">
    <h1>Welcome to <%= PAGE_NAME %></h1>
    <h2>
      <%= PAGE_NAME %> is a Festival Video game to be played by festival goers

    </h2>
    <% if !signed_in? %>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
    <%  end %>
  </div>
</div>

app/views/home/client.html.erb
<div class="clientWrapper">

	<div class="roundedNav"></div>
	<div class="logoRadioClient"></div>
	<div class="loginHeader"></div>
	<div class="loginWrapper">
		<h3>
			username:<input type="text" class="loginField">
		</h3>
		<h3>
			password:<input type="password" class="loginField">
		</h3>
	</div>

	<div class="navTextWrapper">
    	<h2><%= link_to "the work", work_path %></h2>
    	<h2><%= link_to "the team", team_path %></h2>
    	<h2><%= link_to "contact", contact_path %></h2>
    	<h2 class="navSelected"><%= link_to "client", client_path %></h2>
  	</div>
</div>

app/views/home/contact.html.erb
<div class="contactWrapper">
	<div class="roundedNav"></div>
	<div class="navTextWrapper">
    	<h2><%= link_to "the work", work_path %></h2>
    	<h2><%= link_to "the team", team_path %></h2>
    	<h2 class="navSelected"><%= link_to "contact", contact_path %></h2>
    	<h2><%= link_to "client", client_path %></h2>
  	</div>
	<div class="contactPaper"></div>
	<div class="contactBackground"></div>
	<div class="contactAddress">
		<h3>
			Ketchum Labs<br />
			533 S. Los Angeles St<br />
			Suite 405<br />
			Los Angeles, CA 90013<br />
			Work: 213.612.0370<br />
			Fax: 213.341.2347<br />
			<a href="mailto:hi@ketchumlabs.com">hi@ketchumlabs.com</a><br />
		</h3>
	</div>
	<div class="contactDisclaimer">
		<h4>
			Please note that Ketchum Labs does not accept unsolicited submissions of any kind. Any submissions that are sent to us will be kindly discarded.
		</h4>
	</div>
</div>

app/views/home/index.html.erb
<div class="navWrapper">
  <div class="roundedNav"></div>
  <div class="kids"></div>
  <!--! <div class="navBackgroundFull"></div>-->
  <div class="navBackground"></div> 

  <div class="navLeftBackground"></div>
  <div class="navTextWrapper">
    <h2><%= link_to "the work", work_path %></h2>
    <h2><%= link_to "the team", team_path %></h2>
    <h2><%= link_to "contact", contact_path %></h2>
    <h2><%= link_to "client", client_path %></h2>
  </div>
</div>

<div class="hoverWrapper">
    <div class="weatherHover hoverSlide rotate45">
    <a href="http://www.weather.com/weather/tenday/Ketchum+ID+83340:4:US" target="_blank"></a>
</div>
  <div class="contactHover hoverSlide rotate45"><%= link_to "", contact_path %></div>
  <div class="teamHover hoverSlide rotate45"><%= link_to "", team_path %></div>
  <div class="clientHover hoverSlide rotate45"><%= link_to "", client_path %></div>
  <div class="filmHover hoverSlide rotate45"><%= link_to "", work_path(q: "film") %></div>
  <div class="televisionHover hoverSlide rotate45"><%= link_to "", work_path(q: "television") %></div>
  <div class="digitalHover hoverSlide rotate45"><%= link_to "", work_path( q: "digital") %></div>
  <div class="yardsaleHover hoverSlide rotate45">
    <a href="http://www.youtube.com/watch?v=bVhCefQL-fs" target="_blank"></a>
  </div>
</div>

<div class="fillBlocks">
  <div class="fillBlock fillYardsale">
    <%= image_tag "yardsaleBlock.png" %>
  </div>
  <div class="fillBlock fillDigital">
    <%= image_tag "digitalBlock2.png" %>
  </div>
  <div class="fillBlock fillTelevision">
    <%= image_tag "televisionBlock.png" %>
  </div>
  <div class="fillBlock fillClient">
    <%= image_tag "clientBlock2.png" %>
  </div>
  <div class="fillBlock fillTeam">
    <%= image_tag "teamBlock.png" %>
  </div>
  <div class="fillBlock fillWeather">
    <%= image_tag "weatherBlock.png" %>
  </div>
</div>


<div class="hoverImages">
  <div class="teamBlock slideBlock">
    <a href="#"><%= image_tag "teamBlock.png" %></a>
  </div>
  <div class="televisionBlock slideBlock">
    <a href="#"><%= image_tag "televisionBlock.png" %></a>
  </div>
  <div class="yardsaleBlock slideBlock">
    <a href="#"><%= image_tag "yardsaleBlock.png" %></a>
  </div>
  <div class="weatherBlock slideBlock">
    <a>
      <%= image_tag "weatherBlock.png" %>
    </a>
  </div>
  <div class="contactBlock slideBlock">
    <a href="#"><%= image_tag "contactBlock.png" %></a>
  </div>
  <div class="clientBlock slideBlock">
    <a href="#"><%= image_tag "clientBlock2.png" %></a>
  </div>
  <div class="clientBlocker"><%= image_tag "greenBlocker.png" %></div>
  <div class="filmBlock slideBlock">
    <a href="#"><%= image_tag "filmBlock.png" %></a>
  </div>
  <div class="filmBlocker"><%= image_tag "greenBlocker.png" %></div>
  <div class="digitalBlock slideBlock">
    <a href="#"><%= image_tag "digitalBlock2.png" %></a>
  </div>
  <div class="digitalBlocker"><%= image_tag "greenBlocker.png" %></div> 
  <div class="endPanel"></div>
</div>

<div class="blockShadow contactShadow"></div>

<div class="slidersWrapper">
  <div class="weatherSlider"></div>
  <div class="contactSlider"></div>
  <div class="teamSlider"></div>
  <div class="clientSlider"></div>
  <div class="filmSlider"></div>
  <div class="televisionSlider"></div>
  <div class="digitalSlider"></div>
  <div class="yardsaleSlider"></div>
</div>

<div class="arrowsWordsWrapper">
  <div class="wordWeather"></div>
  <div class="arrowWeather"></div>
  <div class="wordContact"></div>
  <div class="arrowContact"></div>
  <div class="wordTheTeam"></div>
  <div class="arrowTheTeam"></div>
  <div class="wordClient"></div>
  <div class="arrowClient"></div>
  <div class="wordFilm"></div>
  <div class="arrowFilm"></div>
  <div class="wordTelevision"></div>
  <div class="arrowTelevision"></div>
  <div class="wordTelevision"></div>
  <div class="arrowTelevision"></div>
  <div class="wordDigital"></div>
  <div class="arrowDigital"></div>
  <div class="wordYardsale"></div>
  <div class="arrowYardsale"></div>
</div>

<div class="headerWrapper">
  <ul>
    <li><%= link_to "home", home_path %></li> 
    <li><%= link_to "the work", work_path %></li>
    <li><%= link_to "the team", team_path %></li>
    <li><%= link_to "contact", contact_path %></li>
    <li><%= link_to "client", client_path %></li>
  </ul>
</div>

app/views/home/index.mobile.erb
<ul>
  <% for user in @users %>
    <li class="arrow">
      <%= link_to h(user.name), user %>
      <small class="counter"><%= user.name %></small>
    </li>
  <% end %>
</ul>

<ul><li class="arrow"><%= link_to "New Project", new_user_path %></li></ul>

app/views/home/team.html.erb
<div class="teamWrapper">
	<div class="roundedNav"></div>
	<div class="backgroundTeam"></div>
	<div class="teamPaper"></div>
	<div class="photoTeam"></div>
	<div class="snowmobile"></div>

	<div class="teamNavText">
		<h2>
			<a href="#kechumBio" data-toggle="tab">
				<span class="boldCaps title colorLink navSelected">KETCHUM LABS</span>
			</a>
		</h2>
		<h2> 
			<a href="#kevinBio" data-toggle="tab">
				<span class="boldCaps">&#x95; Kevin Abrams: </span>
				Principal
			</a>
		</h2>
		<h2>
			<a href="#patrickBio" data-toggle="tab">
				<span class="boldCaps">
				&#x95; Patrick Weir: 
				</span>
				Principal
			</a>
		</h2>
		<h2>
			<a href="#mauryBio" data-toggle="tab">
				<span class="boldCaps">
				&#x95; Maury Gallagher: 
				</span>
				Partner
			</a>
		</h2>
	</div>

	<div class="teamBluePaperFull">
		<div class="tab-content">
			<div class="tab-pane active" id="kechumBio">
				<h4>
					KETCHUM LABS was founded in 2011 by Kevin Abrams, Patrick Weir and Maury Gallagher. Presently, Ketchum Labs is in post-production on the feature documentary <a href="http://www.ketchumlabs.com/videos/103546708330517">"The Other Shore"</a>, chronicling Diana Nyad's attempt to be become the first person to swim from The Florida Keys to Cuba without a shark cage. KL is also in production on the unscripted series <a href="http://www.ketchumlabs.com/videos/102546708330517">“Chasing Spencer”</a>, the first rookie-eyed look at life as an aspiring Nascar driver. Ketchum Labs is represented by William Morris Endeavor.
				</h4>
			</div>
			<div class="tab-pane" id="kevinBio">
				<h4>
					KEVIN ABRAMS (Principal/Executive Producer): A graduate of the University of 	Pennsylvania and a recipient of an MFA in directing from the prestigious 	American Film Institute, Kevin has worked in film and television for the past 	fifteen years. From editing to producing, to sound, to cinematography, Kevin 	has been involved in programming that has appeared on PBS, Discovery, MTV, 	ABC, VH1, Animal Planet and a host of other networks. He has worked in 	editorial on the Emmy-nominated Whale Wars as well as on the Oscar-nominated 	documentary feature “Daughter of Danang”.
				</h4>
				<h4>
					In 2006 Kevin founded the multi-media production company Fairtrade Films which 	has since produced music videos, created video game installations for 	Disney/Epcot Center, wrote the best-selling video games, “Ratchet and Clank: 	Tools of Dustruction” and “Dirt 3”, and authored the acclaimed graphic novel, 	"Vendor". In addition, Fairtrade Films has set-up fiction shows with Landscape 	Entertainment, Freemantle Entertainment and Kaplan Entertainment. Recently, 	Fairtrade saw the release of their first produced feature, “The Dynamiter” 	which had its world premiere at the esteemed 2011 Berlin Film Festival and its 	North American premiere at the 2011 Los Angeles Film Festival, and was 	nominated for Best Feature Under 500k and Cinematography at the 2012 	Independent Spirit Awards.
				</h4>
			</div>
		<div class="tab-pane" id="patrickBio">
			<h4>
				PATRICK WEIR (Principal/Executive Producer): Patrick began his career at CNET Networks (cnet.com) as a Producer in their Advertising Development group in the late 1990’s.  Working with CNET’s premiere advertisers including Sony, Microsoft, Oracle and HP, Weir and his team pioneered the first wave of Flash-based video and interactive advertising across CNET’s properties: CNET, ZDNet, GameSpot & TechRepublic.
			</h4>
			<h4>
				Weir segued into television and joined Fox Cable Network's action sports and music network, FUEL TV, as a staff producer/editor.  The first few years were spent producing and editing Fuel TV's marquee show, Firsthand, a half-hour unscripted series featuring the world’s best surfing, skateboarding, snowboarding and freestyle motocross athletes. He later developed and ran FUEL TV's studio daily show –The Daily Habit– producing over 500 shows.
			</h4>
			<h4>
				Opting for a wider range of projects, Weir left FUEL TV and currently produces unscripted and commercial content across all platforms. His clients include Fox, Saatchi & Saatchi, BermanBraun, MSN, G4, NBC, Red Bull, Toyota, Truth, Mt. Dew and Adidas.
			</h4>
		</div>
		<div class="tab-pane" id="mauryBio">
			<h4>
				MAURY GALLAGHER (Partner/Principal Investor): Maurice J. Gallagher, Jr. is a Principal at Gallagher Corporation, Gallagher Equity Management and Co-Partner of the investment firm at Flynn/Gallagher. He also serves an Advisor at Blue Beacon Capital LLC. Mr. Gallagher provides senior management direction to companies that include Telecommunications and Internet applications service provider companies. In early 1996, he co-founded Mpower Communications. 
			</h4>
			<h4>
				From September 2001 to the present, Mr. Gallagher serves as Chairman of Allegiant Airlines. He was also a Chairman of the Board of Mpower Communications. Prior to Mpower, Mr. Gallagher founded ValuJet Airlines. Previously, he was a Founder and President at WestAir Holding. Mr. Gallagher also helped launch PurchasePro.com and BankServ. He is a graduate from the University of California at Davis with a Bachelor of Arts in History and holds an M.B.A. from the University of California at Berkeley.
			</h4>
		</div>
	</div>
	</div>
	<div class="navTextWrapper">
    	<h2><%= link_to "the work", work_path %></h2>
    	<h2 class="navSelected"><%= link_to "the team", team_path %></h2>
    	<h2><%= link_to "contact", contact_path %></h2>
    	<h2><%= link_to "client", client_path %></h2>
  	</div>
</div>

<script type="text/javascript">

$('.teamNavText h2 a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
    highlightActive(this)
    //$('.tab-content h4').animate({
    //  opacity: '.3'
    //  }, 2000
    //);
});

$(function() {
   $('a[data-toggle="tab"]').on('show', function (e) {
   		$('.tab-content').toggle(700); 
    })
});

function highlightActive(activeItem) {
    $('.teamNavText h2 a span').removeClass('colorLink'); 
    $(activeItem).children("span:first").addClass('colorLink');
};


</script>

app/views/home/work.html.erb
<div class="workWrapper">
	<div class="roundedNav"></div>
	<div class="logoDots"></div>

 <%= render :partial => 'videoSelector' %>

	<div class="navTextWrapper">
    	<h2  class="navSelected"><%= link_to "the work", work_path %></h2>
    	<h2><%= link_to "the team", team_path %></h2>
    	<h2><%= link_to "contact", contact_path %></h2>
    	<h2><%= link_to "client", client_path %></h2>
  </div>
  	
</div> <!--! --End workWrapper - -->



<script>
  $(function() {
    var selector = "<%= @filter %>";    
    $(selector + "Check").show(300);
    if (selector == ".all") {
      $('.allCheck').show(300);
    } else {
      $('.carousel').carousel('pause');
		  $('.clearBox').css('z-index' , '200');		
		  $(selector).css('z-index', '100');
	  }
    
    // if film television of digital is clicke
    // insert q: @filter into href's backButton & forwardButton   

    //
    //
    //
  });


</script>